//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingRecords
    {
        public AccountingRecords()
        {
            this.AccountsReceivable = new HashSet<AccountsReceivable>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public short Debit { get; set; }
        public short Credit { get; set; }
        public int MemberId { get; set; }
        public int RegisteredId { get; set; }
        public Nullable<System.Guid> DebitGuidId { get; set; }
        public Nullable<System.Guid> CreditGuidId { get; set; }
        public Nullable<long> DebitLongId { get; set; }
        public Nullable<long> CreditLongId { get; set; }
    
        public virtual EsMembers EsMembers { get; set; }
        public virtual EsUsers EsUsers { get; set; }
        public virtual ICollection<AccountsReceivable> AccountsReceivable { get; set; }
    }
}
