//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archived_ProductItems
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid CreatedInvoiceId { get; set; }
        public Nullable<System.Guid> DeliveryInvoiceId { get; set; }
        public short StockId { get; set; }
        public int MemberId { get; set; }
    }
}
