//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.MembersBrands = new HashSet<MembersBrands>();
            this.Products = new HashSet<Products>();
        }
    
        public long Id { get; set; }
        public string BrandName { get; set; }
        public string BrandDescription { get; set; }
        public string LogoPath { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MembersBrands> MembersBrands { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
