//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.ProductCategories = new HashSet<ProductCategories>();
        }
    
        public long Id { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentCategoryId { get; set; }
        public string LogoPath { get; set; }
    
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
    }
}
