//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsCategories
    {
        public EsCategories()
        {
            this.EsCategories1 = new HashSet<EsCategories>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HCDCS { get; set; }
        public string Logo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public long LastModifierId { get; set; }
    
        public virtual ICollection<EsCategories> EsCategories1 { get; set; }
        public virtual EsCategories EsCategories2 { get; set; }
    }
}
