//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsDefaults
    {
        public System.Guid Id { get; set; }
        public string Control { get; set; }
        public Nullable<System.Guid> ValueInGuid { get; set; }
        public Nullable<long> ValueInLong { get; set; }
        public int MemberId { get; set; }
    }
}
