//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsInvoiceItemsArchive
    {
        public System.Guid ID { get; set; }
        public System.Guid EsInvoiceID { get; set; }
        public System.Guid ESProductID { get; set; }
        public Nullable<System.Guid> ProductItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Description { get; set; }
    }
}
