//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsMembersAccounts
    {
        public int MemberId { get; set; }
        public decimal TotalScores { get; set; }
        public bool IsActive { get; set; }
        public decimal Deposite { get; set; }
        public decimal Credit { get; set; }
        public int LicenseId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string TIN { get; set; }
        public string BankAccount { get; set; }
        public string Bank { get; set; }
        public string Description { get; set; }
    }
}
