//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsmMeasureOfUnits
    {
        public short Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public Nullable<bool> IsWeight { get; set; }
        public Nullable<short> GroupId { get; set; }
    }
}
