//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESSharedProducts
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OriginalId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Code { get; set; }
        public string Barcode { get; set; }
        public string HCDCS { get; set; }
        public string Description { get; set; }
        public Nullable<short> MeasureOfunitId { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DealerPrice { get; set; }
        public Nullable<decimal> DealerDiscount { get; set; }
        public Nullable<decimal> MinQuantity { get; set; }
        public Nullable<short> ExpiryDays { get; set; }
        public int EsMemberId { get; set; }
        public Nullable<int> LastModifierId { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    }
}
