//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogForProducts
    {
        public System.Guid Id { get; set; }
        public short Action { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid ProductId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsEmpty { get; set; }
        public int ModifierId { get; set; }
        public int MemberId { get; set; }

        public LogForProducts()
        {
            Id = Guid.NewGuid();
        }
    }
}
