//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItems
    {
        public ProductItems()
        {
            this.ProductItems1 = new HashSet<ProductItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> ParentProductItemId { get; set; }
        public System.Guid CreatedInvoiceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> DeliveryInvoiceId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<short> StockId { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CoordinateX { get; set; }
        public string CoordinateY { get; set; }
        public string CoordinateZ { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReservedById { get; set; }
        public int MemberId { get; set; }
    
        public virtual EsStock EsStock { get; set; }
        public virtual ICollection<ProductItems> ProductItems1 { get; set; }
        public virtual ProductItems ProductItems2 { get; set; }
        public virtual Products Products { get; set; }
    }
}
