//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderItems
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductOrderId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public long LastModifierId { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Mu { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
    
        public virtual EsUsers EsUsers { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
        public virtual ProductOrderItems ProductOrderItems1 { get; set; }
        public virtual ProductOrderItems ProductOrderItems2 { get; set; }
        public virtual Products Products { get; set; }
    }
}
