//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategories
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public long CategoryId { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
