//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItems
    {
        public ProductItems()
        {
            this.InvoiceItems = new HashSet<InvoiceItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid DeliveryInvoiceId { get; set; }
        public Nullable<long> StockId { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CoordinateX { get; set; }
        public string CoordinateY { get; set; }
        public string CoordinateZ { get; set; }
        public string Description { get; set; }
        public Nullable<long> ReservedById { get; set; }
        public long MemberId { get; set; }
    
        public virtual EsMembers EsMembers { get; set; }
        public virtual EsUsers EsUsers { get; set; }
        public virtual ICollection<InvoiceItems> InvoiceItems { get; set; }
        public virtual ProductItems ProductItems1 { get; set; }
        public virtual ProductItems ProductItems2 { get; set; }
        public virtual Products Products { get; set; }
        public virtual EsStock EsStock { get; set; }
    }
}
