//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public ProductOrder()
        {
            this.ProductOrderItems = new HashSet<ProductOrderItems>();
        }
    
        public System.Guid Id { get; set; }
        public int EsMemberId { get; set; }
        public string OrderNumber { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> RsponsibleId { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> InProgress { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual EsMembers EsMembers { get; set; }
        public virtual EsUsers EsUsers { get; set; }
        public virtual EsUsers EsUsers1 { get; set; }
        public virtual ICollection<ProductOrderItems> ProductOrderItems { get; set; }
    }
}
