//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeItems
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Index { get; set; }
        public System.Guid StockTakeId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string CodeOrBarcode { get; set; }
        public string ProductDescription { get; set; }
        public string Mu { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> StockTakeQuantity { get; set; }
        public System.DateTime StockTakeDate { get; set; }
    
        public virtual StockTake StockTake { get; set; }
    }
}
