//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTake
    {
        public StockTake()
        {
            this.StockTakeItems = new HashSet<StockTakeItems>();
        }
    
        public System.Guid Id { get; set; }
        public long MemberId { get; set; }
        public Nullable<long> StockId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<long> StockTakeNumber { get; set; }
        public long CreatorId { get; set; }
        public Nullable<long> ModifierId { get; set; }
        public Nullable<long> CloserId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<StockTakeItems> StockTakeItems { get; set; }
    }
}
