//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAccountingPlan
    {
        public System.Guid Id { get; set; }
        public int AccountingPlanId { get; set; }
        public Nullable<int> SubAccountingPlanId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public long MemberId { get; set; }
        public bool IsActive { get; set; }
    }
}
