//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.UploadEstateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadEstateService.IUploadService")]
    public interface IUploadService {
        
        // CODEGEN: Generating message contract since the wrapper name (EstateData) of message EstateData does not match the default value (UploadEstate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadEstate", ReplyAction="http://tempuri.org/IUploadService/UploadEstateResponse")]
        Shared.UploadEstateService.ReturnData UploadEstate(Shared.UploadEstateService.EstateData request);
        
        // CODEGEN: Generating message contract since the wrapper name (EstateImageData) of message EstateImageData does not match the default value (UploadImage)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadImage", ReplyAction="http://tempuri.org/IUploadService/UploadImageResponse")]
        Shared.UploadEstateService.ReturnData UploadImage(Shared.UploadEstateService.EstateImageData request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstateData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EstateData {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Realtor.DTO.EstateDto Estate;
        
        public EstateData() {
        }
        
        public EstateData(string Header, Realtor.DTO.EstateDto Estate) {
            this.Header = Header;
            this.Estate = Estate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnData {
        
        public ReturnData() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstateImageData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EstateImageData {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int EstateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageStream;
        
        public EstateImageData() {
        }
        
        public EstateImageData(int EstateID, System.IO.Stream ImageStream) {
            this.EstateID = EstateID;
            this.ImageStream = ImageStream;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadServiceChannel : Shared.UploadEstateService.IUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceClient : System.ServiceModel.ClientBase<Shared.UploadEstateService.IUploadService>, Shared.UploadEstateService.IUploadService {
        
        public UploadServiceClient() {
        }
        
        public UploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shared.UploadEstateService.ReturnData Shared.UploadEstateService.IUploadService.UploadEstate(Shared.UploadEstateService.EstateData request) {
            return base.Channel.UploadEstate(request);
        }
        
        public void UploadEstate(string Header, Realtor.DTO.EstateDto Estate) {
            Shared.UploadEstateService.EstateData inValue = new Shared.UploadEstateService.EstateData();
            inValue.Header = Header;
            inValue.Estate = Estate;
            Shared.UploadEstateService.ReturnData retVal = ((Shared.UploadEstateService.IUploadService)(this)).UploadEstate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shared.UploadEstateService.ReturnData Shared.UploadEstateService.IUploadService.UploadImage(Shared.UploadEstateService.EstateImageData request) {
            return base.Channel.UploadImage(request);
        }
        
        public void UploadImage(int EstateID, System.IO.Stream ImageStream) {
            Shared.UploadEstateService.EstateImageData inValue = new Shared.UploadEstateService.EstateImageData();
            inValue.EstateID = EstateID;
            inValue.ImageStream = ImageStream;
            Shared.UploadEstateService.ReturnData retVal = ((Shared.UploadEstateService.IUploadService)(this)).UploadImage(inValue);
        }
    }
}
